package modeloa.support;

public enum NotifikazioMotak {
	IZENA_BATERAEZINA,
	LOGIN_ZUZENA,
	TAULA_EGUNERATU,
	HAUTAGAIAK_EGUNERATU,
	EMAITZA_ONDO_DAGO,
	EMAITZA_TXARTO_DAGO,
	EZIN_IZAN_DA_SUDOKUA_SORTU,
	EZIN_DA_BALIOA_ALDATU,
	LAGUNTZA_IRUDIKATU,
	RANKING_EGUNERATU,
	AMAIERA_ITXI
}
